# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. It is used to install promptmatch
class Promptmatch < Formula
  desc "Train your AI prompting skills by recreating hidden images"
  homepage "https://github.com/TheRichArcher/promptmatch"
  # Use archive download instead of git clone to avoid GitHub 500 errors
  url "https://github.com/TheRichArcher/promptmatch/archive/refs/heads/main.tar.gz"
  version "0.1.0"
  sha256 :no_check
  license "MIT"

  depends_on "node"
  depends_on "pnpm"

  def install
    # Install dependencies
    system "pnpm", "install", "--no-frozen-lockfile"
    
    # Install the project files
    prefix.install Dir["*"]
    
    # Create a wrapper script to run the dev server
    (bin/"promptmatch").write <<~EOS
      #!/bin/bash
      cd #{prefix}
      exec pnpm dev "$@"
    EOS
    chmod 0755, bin/"promptmatch"
  end

  test do
    system "true"
  end
end

